code : '*da211eb*c4dd1*d'
index: 9
jiahao: 0123456789
pass2: 超级鹰密码
regemail: 注册邮箱
regname: 注册用户名
regpwd: 注册密码
softid: 超级鹰应用ID
url: https://www.t66y.com/register.php?
user: 超级鹰账号
validateUrl: https://www.t66y.com/require/codeimg.php?0.
wenhao: 0123456789abcdef
xinghao: abcdef
